SELECT u.NOME, l.TITULO, a.DATA_ALUGUEL, a.DATA_DEVOLUCAO, a.DEVOLVIDO FROM Aluguel a

INNER JOIN Usuarios u
ON u.ID_USUARIO = a.ID_USUARIO

INNER JOIN Livros l
ON l.ID_LIVRO = a.ID_LIVRO

SELECT NOME, EMAIL, a.ID_LIVRO
FROM Usuarios u

LEFT JOIN Aluguel a
ON u.ID_USUARIO = a.ID_USUARIO