-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.

CREATE DATABASE aula09_ex002
GO

USE aula09_ex002
GO

CREATE TABLE Usuarios (
	ID_USUARIO Int PRIMARY KEY,
	NOME nvarchar(50),
	TELEFONE varchar(14),
	EMAIL nvarchar(30)
)

CREATE TABLE Autores (
	ID_AUTOR Int PRIMARY KEY,
	NOME nvarchar(30),
	SOBRENOME nvarchar(30)
)

CREATE TABLE Livros (
	ISBN Int PRIMARY KEY,
	TITULO nvarchar(50),
	DATA_PUBLICACAO date
)

CREATE TABLE Categorias (
	ID_CATEGORIA Int PRIMARY KEY,
	NOME nvarchar(50)
)

CREATE TABLE Livro_Categoria (
	ID_CATEGORIA Int,
	ISBN Int,
	FOREIGN KEY(ID_CATEGORIA) REFERENCES Categorias (ID_CATEGORIA) ON UPDATE CASCADE,
	FOREIGN KEY(ISBN) REFERENCES Livros (ISBN) ON UPDATE CASCADE
)

CREATE TABLE Aluguel (
	ID_ALUGUEL Int PRIMARY KEY,
	ID_USUARIO Int,
	ISBN Int,
	DATA_LOCACAO date,
	DATA_DEVOLUCAO_PREVISTA date,
	DATA_DEVOLUCAO_REAL date,
	FOREIGN KEY(ISBN) REFERENCES Livros (ISBN) ON UPDATE CASCADE,
	FOREIGN KEY(ID_USUARIO) REFERENCES Usuarios (ID_USUARIO) ON UPDATE CASCADE
)

CREATE TABLE Livro_Autor (
	ID_AUTOR Int,
	ISBN Int,
	FOREIGN KEY(ID_AUTOR) REFERENCES Autores (ID_AUTOR) ON UPDATE CASCADE,
	FOREIGN KEY(ISBN) REFERENCES Livros (ISBN) ON UPDATE CASCADE
)