-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.

CREATE DATABASE Aula09
GO

USE Aula09
GO

CREATE TABLE Estado (
ID_ESTADO Int PRIMARY KEY,
SIGLA Char(2)
)

CREATE TABLE Cidade (
ID_CIDADE Int PRIMARY KEY,
ID_ESTADO Int,
NOME Nvarchar(50),
FOREIGN KEY(ID_ESTADO) REFERENCES Estado (ID_ESTADO) ON UPDATE CASCADE
)

CREATE TABLE Aluno (
ID_ALUNO Int PRIMARY KEY,
ID_CIDADE Int,
NOME Nvarchar(50),
NASCIMENTO Date,
RUA Nvarchar(50),
NUMERO Int,
TELEFONE Varchar(16),
FOREIGN KEY(ID_CIDADE) REFERENCES Cidade (ID_CIDADE) ON UPDATE CASCADE
)

CREATE TABLE Turma (
ID_TURMA Int PRIMARY KEY,
NOME Nvarchar(50),
VAGAS Int
)

CREATE TABLE Matricula (
ID_MATRICULA Int PRIMARY KEY,
ID_TURMA Int,
ID_ALUNO Int,
SITUACAO Bit,
FOREIGN KEY(ID_TURMA) REFERENCES Turma (ID_TURMA) ON DELETE CASCADE,
FOREIGN KEY(ID_ALUNO) REFERENCES Aluno (ID_ALUNO) ON DELETE CASCADE
)