USE master
GO

-- Deletando o banco com segurança se ele já existir
IF DB_ID('Aula13_ex001') IS NOT NULL 
BEGIN
	ALTER DATABASE Aula13_ex001
	SET SINGLE_USER WITH ROLLBACK IMMEDIATE

	DROP DATABASE Aula13_ex001
END
GO

CREATE DATABASE Aula13_ex001
GO

USE Aula13_ex001
GO

-- Criando as tabelas
CREATE TABLE Categorias (
	ID_CATEGORIA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	DESCRICAO_CATEGORIA NVARCHAR(50) NOT NULL
)

CREATE TABLE Produtos (
	ID_PRODUTO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOME_PRODUTO NVARCHAR(50) NOT NULL,
	DESCRICAO NVARCHAR(200) NOT NULL,
	ID_CATEGORIA INT NOT NULL,

	CONSTRAINT FK_PRODUTOS_CATEGORIA FOREIGN KEY(ID_CATEGORIA) REFERENCES Categorias(ID_CATEGORIA)
)

CREATE TABLE Estoque (
	ID_ESTOQUE INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ID_PRODUTO INT NOT NULL,
	QTD_ESTOQUE INT NOT NULL,

	CONSTRAINT FK_ESTOQUE_PRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES Produtos(ID_PRODUTO)
)

CREATE TABLE Producao (
	ID_PRODUCAO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	QTD_PRODUZIDA INT NOT NULL,
	DATA_PRODUCAO DATETIME NOT NULL,
	ID_PRODUTO INT NOT NULL,

	CONSTRAINT FK_PRODUCAO_PRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES Produtos(ID_PRODUTO)
)

CREATE TABLE Vendas (
	ID_VENDA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ID_PRODUTO INT NOT NULL,
	QTD_VENDIDA INT NOT NULL,
	DATA_VENDA DATETIME NOT NULL,

	CONSTRAINT FK_VENDAS_PRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES Produtos(ID_PRODUTO)
)