USE Aula15_projetoFinal
GO

CREATE PROCEDURE MostraPedidos
AS
BEGIN
	SELECT p.ID_PEDIDO COD_PEDIDO, f.NOME_FORNECEDOR FORNECEDOR, t.DESCRICAO_TRABALHO TRABALHO, func.NOME_FUNCIONARIO FUNCIONARIO, pro.NOME_PRODUTO PRODUTO, p.DATA_SOLICITACAO, p.DATA_ATENDIDO FROM Pedido p
	INNER JOIN Fornecedor f
	ON f.ID_FORNECEDOR = p.ID_FORNECEDOR
	INNER JOIN Trabalho t
	ON t.ID_TRABALHO = p.ID_TRABALHO
	INNER JOIN Funcionario func
	ON func.ID_FUNCIONARIO = p.ID_FUNCIONARIO
	INNER JOIN Produto pro
	ON pro.ID_PRODUTO = p.ID_PRODUTO
END
GO

CREATE PROCEDURE SelecionaAtualizaPedido
	@idPedido INT = NULL
AS
BEGIN
	IF @idPedido IS NULL
	BEGIN
		EXEC MostraPedidos
	END
	ELSE
	BEGIN
		UPDATE Pedido
		SET DATA_ATENDIDO = GETDATE()
		WHERE ID_PEDIDO = @idPedido

		EXEC MostraPedidos
	END
END
GO