/* modeloLogico_normalizado: */

CREATE TABLE Fornecedor (
    ID_FORNECEDOR INT NOT NULL PRIMARY KEY,
    NOME_FORNECEDOR VARCHAR(50) NOT NULL,
    ID_ENDERECO INT NOT NULL,
    DESCRICAO_FORNECEDOR VARCHAR(200) NOT NULL
);

CREATE TABLE Produto (
    ID_PRODUTO INT NOT NULL PRIMARY KEY,
    NOME_PRODUTO VARCHAR(50) NOT NULL,
    DESCRICAO_PRODUTO VARCHAR(100) NOT NULL
);

CREATE TABLE Funcionario (
    ID_FUNCIONARIO INT NOT NULL,
    NOME_FUNCIONARIO VARCHAR(50) NOT NULL,
    ID_ENDERECO INT NOT NULL,
    FUNCAO VARCHAR(50) NOT NULL
);

CREATE TABLE Trabalho (
    ID_TRABALHO INT NOT NULL PRIMARY KEY,
    ID_ENDERECO INT NOT NULL,
    PROPRIETARIO VARCHAR(50) NOT NULL,
    DESCRICAO_TRABALHO VARCHAR(100) NOT NULL
);

CREATE TABLE Endereco (
    ID_ENDERECO INT NOT NULL PRIMARY KEY,
    RUA VARCHAR(50) NOT NULL,
    NUMERO VARCHAR(7) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    COMPLEMENTO VARCHAR(50) NOT NULL,
    ID_CIDADE INT NOT NULL,
    CEP VARCHAR(10) NOT NULL
);

CREATE TABLE Cidade (
    ID_CIDADE INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    ID_ESTADO INT NOT NULL
);

CREATE TABLE Estado (
    ID_ESTADO INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    SIGLA CHAR(2) NOT NULL
);

CREATE TABLE Pedido (
    ID_PEDIDO INT NOT NULL PRIMARY KEY,
    ID_FORNECEDOR INT NOT NULL,
    ID_TRABALHO INT NOT NULL,
    ID_FUNCIONARIO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    DATA_SOLICITACAO DATETIME NOT NULL,
    DATA_ATENDIDO DATETIME NOT NULL
);
 
ALTER TABLE Fornecedor ADD CONSTRAINT FK_Fornecedor_2
    FOREIGN KEY (ID_ENDERECO)
    REFERENCES Endereco (ID_ENDERECO)
    ON DELETE CASCADE;
 
ALTER TABLE Funcionario ADD CONSTRAINT FK_Funcionario_2
    FOREIGN KEY (ID_ENDERECO)
    REFERENCES Endereco (ID_ENDERECO)
    ON DELETE CASCADE;
 
ALTER TABLE Trabalho ADD CONSTRAINT FK_Trabalho_1
    FOREIGN KEY (ID_ENDERECO)
    REFERENCES Endereco (ID_ENDERECO)
    ON DELETE CASCADE;
 
ALTER TABLE Endereco ADD CONSTRAINT FK_Endereco_2
    FOREIGN KEY (ID_CIDADE)
    REFERENCES Cidade (ID_CIDADE)
    ON DELETE CASCADE;
 
ALTER TABLE Cidade ADD CONSTRAINT FK_Cidade_2
    FOREIGN KEY (ID_ESTADO)
    REFERENCES Estado (ID_ESTADO)
    ON DELETE CASCADE;
 
ALTER TABLE Pedido ADD CONSTRAINT ID_PRODUTO
    FOREIGN KEY (ID_PRODUTO)
    REFERENCES Produto (ID_PRODUTO)
    ON DELETE RESTRICT;
 
ALTER TABLE Pedido ADD CONSTRAINT ID_FORNECEDOR
    FOREIGN KEY (ID_FORNECEDOR)
    REFERENCES Fornecedor (ID_FORNECEDOR)
    ON DELETE RESTRICT;
 
ALTER TABLE Pedido ADD CONSTRAINT ID_TRABALHO
    FOREIGN KEY (ID_TRABALHO)
    REFERENCES Trabalho (ID_TRABALHO);
 
ALTER TABLE Pedido ADD CONSTRAINT ID_FUNCIONARIO
    FOREIGN KEY (ID_FUNCIONARIO)
    REFERENCES Funcionario (ID_FUNCIONARIO);