USE master
GO

-- Se já existir o banco dessa aula, remove ele de forma segura
IF DB_ID('Aula15_projetoFinal') IS NOT NULL
BEGIN
	ALTER DATABASE Aula15_projetoFinal
	SET SINGLE_USER WITH ROLLBACK IMMEDIATE

	DROP DATABASE Aula15_projetoFinal
END
GO

-- Cria o banco da aula
CREATE DATABASE Aula15_projetoFinal
GO

USE Aula15_projetoFinal
GO

CREATE TABLE Produto (
    ID_PRODUTO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOME_PRODUTO NVARCHAR(50) NOT NULL,
    DESCRICAO_PRODUTO NVARCHAR(100) NOT NULL
);

CREATE TABLE Estado (
    ID_ESTADO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOME NVARCHAR(50) NOT NULL,
    SIGLA CHAR(2) NOT NULL
);

CREATE TABLE Cidade (
    ID_CIDADE INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOME NVARCHAR(50) NOT NULL,
    ID_ESTADO INT NOT NULL,

	CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES Estado(ID_ESTADO)
);

CREATE TABLE Endereco (
    ID_ENDERECO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    RUA NVARCHAR(50) NOT NULL,
    NUMERO NVARCHAR(7) NOT NULL,
    BAIRRO NVARCHAR(50) NOT NULL,
    COMPLEMENTO NVARCHAR(50) NOT NULL,
    ID_CIDADE INT NOT NULL,
    CEP NVARCHAR(10) NOT NULL,

	CONSTRAINT FK_ENDERECO_CIDADE FOREIGN KEY(ID_CIDADE) REFERENCES Cidade(ID_CIDADE)
);

CREATE TABLE Fornecedor (
    ID_FORNECEDOR INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOME_FORNECEDOR NVARCHAR(50) NOT NULL,
    ID_ENDERECO INT NOT NULL,
    DESCRICAO_FORNECEDOR NVARCHAR(200) NOT NULL,

	CONSTRAINT FK_FORNECEDOR_ENDERECO FOREIGN KEY(ID_ENDERECO) REFERENCES Endereco(ID_ENDERECO)
);

CREATE TABLE Trabalho (
    ID_TRABALHO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    ID_ENDERECO INT NOT NULL,
    PROPRIETARIO NVARCHAR(50) NOT NULL,
    DESCRICAO_TRABALHO NVARCHAR(100) NOT NULL,

	CONSTRAINT FK_TRABALHO_ENDERECO FOREIGN KEY(ID_ENDERECO) REFERENCES Endereco(ID_ENDERECO)
);

CREATE TABLE Funcionario (
    ID_FUNCIONARIO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOME_FUNCIONARIO VARCHAR(50) NOT NULL,
    ID_ENDERECO INT NOT NULL,
    FUNCAO VARCHAR(50) NOT NULL,

	CONSTRAINT FK_FUNCIONARIO_ENDERECO FOREIGN KEY(ID_ENDERECO) REFERENCES Endereco(ID_ENDERECO)
);

CREATE TABLE Pedido (
    ID_PEDIDO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    ID_FORNECEDOR INT NOT NULL,
    ID_TRABALHO INT NOT NULL,
    ID_FUNCIONARIO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    DATA_SOLICITACAO DATETIME NOT NULL,
    DATA_ATENDIDO DATETIME NOT NULL,

	CONSTRAINT FK_PEDIDO_FORNECEDOR FOREIGN KEY(ID_FORNECEDOR) REFERENCES Fornecedor(ID_FORNECEDOR),
	CONSTRAINT FK_PEDIDO_TRABALHO FOREIGN KEY(ID_TRABALHO) REFERENCES Trabalho(ID_TRABALHO),
	CONSTRAINT FK_PEDIDO_FUNCIONARIO FOREIGN KEY(ID_FUNCIONARIO) REFERENCES Funcionario(ID_FUNCIONARIO),
	CONSTRAINT FK_PEDIDO_PRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES Produto(ID_PRODUTO)
);